# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3cd4c94334eecd4e2b66a5182465f4dd5c45214b8f328404fbb445d3c7edd2a9c2710da0992b179411349f6ad6643b6c7c396018db6f5c997cb0ed54e707d519

test:
  secret_key_base: 7adc8aa407340774c7cd4b51480a29f8f61e3d420867cb5058393e6994211768734db514a3d4c4cd9ec15a25a82ae1edf9b95f7f675a8e471eb6b2f0d4a6944a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
